name: Flutter Web Deploy

on:
  push:
    branches:
      - main # Sadece main dalına push yapınca çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Paketleri İndir
        run: flutter pub get

      - name: Web Sürümünü Derle
        run: flutter build web --release --base-href "/diceRollingGame/"

      - name: Yayına Al
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web